name : Pages Deployment

on: [push]

env:
  NODE_VERSION: '14.17.3'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build
      run: |
        npm install
        gulp build
    - name: move files
      run : |
        mkdir repo
        rm -rf ./repo/*
        mv ./guide ./repo/
        mv ./resource/* ./repo/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./repo
