name : Pages Deployment

on: [push]

env:
  NODE_VERSION: '14.17.3'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        npm install
        gulp build
#     - name: Deploy Build Files
#       run: |
#         git init
#         git config --global user.email "bsk824@gmail.com"
#         git config --global user.name "Seungki Baek"
#         git add .
#         git commit -am 'deploy'
#         git push
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./resource
